#!/usr/bin/perl -w

use strict;

#use lib $ENV{HOME} . "/mace/perl5";

use Getopt::Long;
use File::Basename;
use lib ((dirname($0) || "."), (dirname($0) || ".")."/../mace-extras/perl5");

use Mace::Util qw{:all};
use Mace::Compiler::MInclude;
#use Mace::Compiler::MIncludeRecDescent;
#use Mace::Compiler::ClassCache;
use Carp;
use Cwd;

my @includes;
Getopt::Long::Configure("bundling");
GetOptions("I=s" => \@includes);

unless (scalar(@ARGV)) {
    die "usage: $0 file [-I path [-I path ...]]\n";
}

$SIG{__DIE__} = sub{ confess $_[0]; };
$SIG{__WARN__} = sub{ confess $_[0]; die; };

BEGIN {
  @main::global_variables = qw($Werror $Wall $Wunusual $Wnounusual $Wdeprecated $Wnodeprecated $Wundefined $Wnoundefined $Wunimplemented $Wnounimplemented);
}
use vars @main::global_variables;

use Mace::Compiler::Globals;
push(@Mace::Compiler::Globals::INCLUDE_PATH, @includes, cwd(), dirname($0)."/../services/interfaces");
$Mace::Compiler::Globals::NUM_WARN = 0;
$Mace::Compiler::Globals::NUM_ERROR = 0;

my $file = shift(@ARGV);

$Mace::Compiler::Globals::filename = $file;

# open(IN, $file) or die "cannot open $file: $!\n";
# my @in = <IN>;
# close(IN);

my @in;

Mace::Compiler::MInclude::expandFile($file, \@in);

print @in;
